--WeaponAbilitiesData.Worm = {
--    TargetMobileEffect = "db_worm",
--    TargetMobileEffectArgs = {
--       Duration = TimeSpan.FromSeconds(1.25),
--        PlayerDuration = TimeSpan.FromSeconds(1.25),
--    },
--  Stamina = 50,
--  Action = {
--      DisplayName = "Worm",
--        Tooltip = "Summon a worm and stun the target for 1.25 seconds.",
--        Icon = "Flame Whirl",
--        Enabled = true
--    },
--    SkipHitAction = true
--}

--WeaponAbilitiesData.lacerate = {
--    MobileEffect = "Stab",
--    MobileEffectArgs = {
--        WeaponAttackModifier = 1.5,
--        HitChanceFront = 0.4,
--        HitChanceBack = 0.8,
--    },
--    Stamina = 10,
--    Action = {
--        DisplayName = "Lacerate",
--        Tooltip = "Increase your attack by 50% of your weapon's attack rating for this stab.",
--        Icon = "Fatal Strike",
--        Enabled = true,
--    },
--    SkipHitAction = true
--}